version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: kara-api
    restart: always
    image: node:14
    working_dir: /usr/application/kara-api
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/application/kara-api/dist
      - ./package.json:/usr/application/kara-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
